//! bash, fish, and PowerShell completions.
//!
//! Three shells, one rule: **nothing is computed at tab time that could have
//! been computed at generation time.** Every closed candidate set is a literal
//! in the script, assigned once when the file is sourced; a keystroke costs a
//! prefix filter over an array already in memory and not one fork.
//!
//! That rule is also what fixes the two real defects in ripgrep's generated
//! bash completion, which are worth naming because they are what a generator
//! that does not know its own flag table produces:
//!
//!   * it offers **file paths after every flag**, including `--word-regexp`
//!     and `--no-heading`, because the generator cannot tell a switch from a
//!     value-taking option. Here the parser's own table says which is which,
//!     so `-w<TAB>` completes flags and `-t<TAB>` completes file types;
//!   * it rebuilds a two-thousand-character option string **inside the
//!     completion function**, on every keystroke, after a loop over
//!     `COMP_WORDS`. Here that string is a top-level assignment.
//!
//! The `--no-…` spellings are withheld until the caller actually types `--no`.
//! ripgrep's zsh function does this by hand, with a prefix pattern its comment
//! admits "has to be updated manually"; here it is a property of the name.

const std = @import("std");
const primer = @import("primer.zig");
const oom = @import("../outcome.zig").oom;

const Choice = primer.Choice;
const Opt = primer.Opt;
const Surface = primer.Surface;

// ── quoting ──────────────────────────────────────────────────────────────

/// Inside a POSIX single-quoted word (bash, zsh): close, escape, reopen.
pub fn sq(buf: *std.ArrayList(u8), gpa: std.mem.Allocator, text: []const u8) void {
    for (text) |c| {
        if (c == '\'') buf.appendSlice(gpa, "'\\''") catch oom() else buf.append(gpa, c) catch oom();
    }
}

/// Inside a fish single-quoted word, where the only escapes are `\'` and `\\`.
fn fq(buf: *std.ArrayList(u8), gpa: std.mem.Allocator, text: []const u8) void {
    for (text) |c| {
        if (c == '\'' or c == '\\') buf.append(gpa, '\\') catch oom();
        buf.append(gpa, c) catch oom();
    }
}

/// Inside a PowerShell single-quoted string, where `'` doubles.
fn pq(buf: *std.ArrayList(u8), gpa: std.mem.Allocator, text: []const u8) void {
    for (text) |c| {
        buf.append(gpa, c) catch oom();
        if (c == '\'') buf.append(gpa, c) catch oom();
    }
}

/// Every spelling of `o`, space-separated, appended as-is.
fn spellings(buf: *std.ArrayList(u8), gpa: std.mem.Allocator, o: Opt, sep: []const u8) void {
    var first = true;
    if (o.short) |s| {
        buf.print(gpa, "-{c}", .{s}) catch oom();
        first = false;
    }
    for (o.longs) |long| {
        if (!first) buf.appendSlice(gpa, sep) catch oom();
        buf.print(gpa, "--{s}", .{long}) catch oom();
        first = false;
    }
}

fn banner(buf: *std.ArrayList(u8), gpa: std.mem.Allocator, s: Surface, target: []const u8, comment: []const u8) void {
    buf.print(gpa,
        \\{s} {s} completion, generated by `{s} --generate {s}`.
        \\{s} Every candidate below is baked in: a completion costs no subprocess.
        \\{s} Do not edit — regenerate after upgrading {s}.
        \\
        \\
    , .{ comment, s.tool, s.tool, target, comment, comment, s.tool }) catch oom();
}

// ── bash ─────────────────────────────────────────────────────────────────

pub fn bash(buf: *std.ArrayList(u8), gpa: std.mem.Allocator, s: Surface) void {
    banner(buf, gpa, s, "complete-bash", "#");
    const sets = primer.distinctSets(gpa, s, "");

    // Sourced once. `_gist_opts` is what `-<TAB>` filters; the negations sit in
    // their own string so the common list stays readable.
    for ([_]bool{ false, true }) |neg| {
        buf.print(gpa, "_{s}_{s}='", .{ s.tool, if (neg) "undo" else "opts" }) catch oom();
        var first = true;
        for (s.opts) |o| {
            if (o.negation() != neg) continue;
            if (!first) buf.append(gpa, ' ') catch oom();
            spellings(buf, gpa, o, " ");
            first = false;
        }
        buf.appendSlice(gpa, "'\n") catch oom();
    }
    if (s.verbs.len > 0) {
        buf.print(gpa, "_{s}_verbs='", .{s.tool}) catch oom();
        for (s.verbs, 0..) |v, i| {
            if (i > 0) buf.append(gpa, ' ') catch oom();
            buf.appendSlice(gpa, v.name) catch oom();
        }
        buf.appendSlice(gpa, "'\n") catch oom();
    }
    for (sets.items) |e| {
        buf.print(gpa, "_{s}_{s}='", .{ s.tool, e.name }) catch oom();
        for (e.choices, 0..) |c, i| {
            if (i > 0) buf.append(gpa, ' ') catch oom();
            sq(buf, gpa, c.word);
        }
        buf.appendSlice(gpa, "'\n") catch oom();
    }

    buf.print(gpa,
        \\
        \\# A baked menu is filtered in-process. `compgen -W` would be shorter and
        \\# would fork a subshell for every keystroke to do the same prefix test
        \\# the shell can do itself; the candidates are single words by
        \\# construction, so the loop is exact.
        \\_{s}_words() {{
        \\  local w
        \\  COMPREPLY=()
        \\  for w in $1; do [[ $w == "$2"* ]] && COMPREPLY+=("$w"); done
        \\}}
        \\# A count or a free-text value: offer nothing rather than a directory
        \\# listing, which is what a generator that cannot read its own flag
        \\# table falls back to.
        \\_{s}_none() {{ COMPREPLY=(); compopt +o default 2> /dev/null; }}
        \\
        \\# Returns 0 when $1 is a value-taking flag and the value was handled.
        \\_{s}_value() {{
        \\  case "$1" in
        \\
    , .{ s.tool, s.tool, s.tool }) catch oom();
    valueArms(buf, gpa, s, sets);
    buf.print(gpa,
        \\    *) return 1 ;;
        \\  esac
        \\}}
        \\
        \\_{s}() {{
        \\  local cur prev
        \\  cur=${{COMP_WORDS[COMP_CWORD]}}
        \\  prev=${{COMP_WORDS[COMP_CWORD-1]}}
        \\  COMPREPLY=()
        \\  # bash breaks a word on `=`, so `--flag=<TAB>` puts the flag two back.
        \\  if [[ $prev == '=' && $COMP_CWORD -ge 2 ]]; then
        \\    _{s}_value "${{COMP_WORDS[COMP_CWORD-2]}}" "$cur"
        \\    return 0
        \\  fi
        \\  _{s}_value "$prev" "$cur" && return 0
        \\  # A short flag may carry its value glued on (`-tzig`), which bash hands
        \\  # over as a single word. Split it and re-offer the value with the flag
        \\  # still on the front, so a half-typed `-t` menus file types instead of
        \\  # dead-ending. A glued switch (`-w`) falls through to the flag list.
        \\  if [[ $cur == -[!-]* ]]; then
        \\    local glued=${{cur:0:2}} i
        \\    if _{s}_value "$glued" "${{cur:2}}"; then
        \\      for i in "${{!COMPREPLY[@]}}"; do COMPREPLY[i]=$glued${{COMPREPLY[i]}}; done
        \\      return 0
        \\    fi
        \\  fi
        \\  if [[ $cur == --no* ]]; then
        \\    _{s}_words "$_{s}_opts $_{s}_undo" "$cur"
        \\    return 0
        \\  fi
        \\  if [[ $cur == -* ]]; then
        \\    _{s}_words "$_{s}_opts" "$cur"
        \\    return 0
        \\  fi
        \\
    , .{ s.tool, s.tool, s.tool, s.tool, s.tool, s.tool, s.tool, s.tool, s.tool }) catch oom();
    if (s.verbs.len > 0) buf.print(gpa,
        \\  if (( COMP_CWORD == 1 )); then
        \\    _{s}_words "$_{s}_verbs" "$cur"
        \\    (( ${{#COMPREPLY[@]}} )) && return 0
        \\  fi
        \\
    , .{ s.tool, s.tool }) catch oom();
    buf.print(gpa,
        \\  return 0
        \\}}
        \\
        \\complete -F _{s} -o bashdefault -o default {s}
        \\
    , .{ s.tool, s.tool }) catch oom();
}

/// bash's own generator for an open value kind, or null when nothing on disk
/// can answer — a count and a regex are not filenames.
fn compgen(of: primer.Candidates) ?u8 {
    return switch (of) {
        .file, .glob => 'f',
        .dir => 'd',
        .command => 'c',
        .number, .open, .listed => null,
    };
}

/// One `case` arm per value-taking flag, grouped so every spelling of a flag
/// shares an arm. Written from the parser's table, which is why a switch never
/// gets one and a path-valued flag never gets a word list.
fn valueArms(buf: *std.ArrayList(u8), gpa: std.mem.Allocator, s: Surface, sets: primer.Sets) void {
    for (s.opts) |o| {
        const v = o.value orelse continue;
        buf.appendSlice(gpa, "    ") catch oom();
        spellings(buf, gpa, o, "|");
        buf.appendSlice(gpa, ") ") catch oom();
        if (sets.find(o)) |name| {
            buf.print(gpa, "_{s}_words \"$_{s}_{s}\" \"$2\"", .{ s.tool, s.tool, name }) catch oom();
        } else if (compgen(v.of)) |kind| {
            buf.print(gpa, "COMPREPLY=( $(compgen -{c} -- \"$2\") )", .{kind}) catch oom();
        } else {
            buf.print(gpa, "_{s}_none", .{s.tool}) catch oom();
        }
        buf.appendSlice(gpa, "; return 0 ;;\n") catch oom();
    }
}

// ── fish ─────────────────────────────────────────────────────────────────

pub fn fish(buf: *std.ArrayList(u8), gpa: std.mem.Allocator, s: Surface) void {
    banner(buf, gpa, s, "complete-fish", "#");
    const sets = primer.distinctSets(gpa, s, "__");

    // fish renders a candidate's gloss in a second column for free, so every
    // baked set ships its descriptions — the reason picking `sjis` out of 220
    // encoding labels is a menu rather than a memory test.
    for (sets.items) |e| {
        buf.print(gpa, "function {s}{s}\n    printf '%s\\n' \\\n", .{ s.tool, e.name }) catch oom();
        for (e.choices) |c| {
            buf.appendSlice(gpa, "        '") catch oom();
            fq(buf, gpa, c.word);
            if (c.doc.len > 0) {
                buf.append(gpa, '\t') catch oom();
                fq(buf, gpa, c.doc);
            }
            buf.appendSlice(gpa, "' \\\n") catch oom();
        }
        buf.appendSlice(gpa, "        ''\nend\n\n") catch oom();
    }

    // `__fish_is_first_arg`, not fish's usual `__fish_use_subcommand`. The
    // latter is written for git, where `git -C dir status` runs the verb, so it
    // skips leading flags — here the verb is argv[1] or it is the pattern, and
    // `gist -w index` searches for "index". Offering a verb there is a menu that
    // lies: it advertises "build and persist the index" for a word that will be
    // read as a regex.
    for (s.verbs) |v| {
        buf.print(gpa, "complete -c {s} -n __fish_is_first_arg -a '", .{s.tool}) catch oom();
        fq(buf, gpa, v.name);
        buf.appendSlice(gpa, "' -d '") catch oom();
        fq(buf, gpa, v.doc);
        buf.appendSlice(gpa, "'\n") catch oom();
        for (v.sub) |c| {
            buf.print(gpa, "complete -c {s} -n '__fish_seen_subcommand_from {s}' -a '", .{ s.tool, v.name }) catch oom();
            fq(buf, gpa, c.word);
            buf.appendSlice(gpa, "' -d '") catch oom();
            fq(buf, gpa, c.doc);
            buf.appendSlice(gpa, "'\n") catch oom();
        }
    }

    for (s.opts) |o| {
        buf.print(gpa, "complete -c {s}", .{s.tool}) catch oom();
        if (o.short) |c| buf.print(gpa, " -s {c}", .{c}) catch oom();
        for (o.longs) |long| buf.print(gpa, " -l {s}", .{long}) catch oom();
        if (o.value) |v| switch (v.of) {
            .file, .glob => buf.appendSlice(gpa, " -r -F") catch oom(),
            .dir => buf.appendSlice(gpa, " -r -F") catch oom(),
            else => {
                buf.appendSlice(gpa, " -x") catch oom();
                if (sets.find(o)) |name| buf.print(gpa, " -a '({s}{s})'", .{ s.tool, name }) catch oom();
            },
        };
        buf.appendSlice(gpa, " -d '") catch oom();
        fq(buf, gpa, o.doc);
        buf.appendSlice(gpa, "'\n") catch oom();
    }
}

// ── PowerShell ───────────────────────────────────────────────────────────

pub fn powershell(buf: *std.ArrayList(u8), gpa: std.mem.Allocator, s: Surface) void {
    banner(buf, gpa, s, "complete-powershell", "#");
    const sets = primer.distinctSets(gpa, s, "");

    buf.appendSlice(gpa,
        \\using namespace System.Management.Automation
        \\
        \\
    ) catch oom();

    // Script-scope, evaluated once when the profile sources this file. Two
    // flags over one registry (`-t` and `-T`) share the array rather than
    // carrying a copy each, which is the difference between a 30 KB file and a
    // 110 KB one for a 239-row type table.
    for (sets.items) |e| {
        buf.print(gpa, "${s}_{s} = @(\n", .{ s.tool, e.name }) catch oom();
        for (e.choices) |c| {
            buf.appendSlice(gpa, "  [CompletionResult]::new('") catch oom();
            pq(buf, gpa, c.word);
            buf.appendSlice(gpa, "', '") catch oom();
            pq(buf, gpa, c.word);
            buf.appendSlice(gpa, "', [CompletionResultType]::ParameterValue, '") catch oom();
            pq(buf, gpa, if (c.doc.len > 0) c.doc else c.word);
            buf.appendSlice(gpa, "')\n") catch oom();
        }
        buf.appendSlice(gpa, ")\n\n") catch oom();
    }

    buf.print(gpa,
        \\Register-ArgumentCompleter -Native -CommandName '{s}' -ScriptBlock {{
        \\  param($wordToComplete, $commandAst, $cursorPosition)
        \\  $elements = $commandAst.CommandElements
        \\  $prev = if ($elements.Count -ge 2) {{ $elements[$elements.Count - 2].ToString() }} else {{ '' }}
        \\  switch ($prev) {{
        \\
    , .{s.tool}) catch oom();
    for (s.opts) |o| {
        const name = sets.find(o) orelse continue;
        var first = true;
        buf.appendSlice(gpa, "    {") catch oom();
        if (o.short) |c| {
            buf.print(gpa, "$_ -eq '-{c}'", .{c}) catch oom();
            first = false;
        }
        for (o.longs) |long| {
            if (!first) buf.appendSlice(gpa, " -or ") catch oom();
            buf.print(gpa, "$_ -eq '--{s}'", .{long}) catch oom();
            first = false;
        }
        buf.print(gpa, "}} {{ return ${s}_{s} | Where-Object {{ $_.CompletionText -like \"$wordToComplete*\" }} }}\n", .{ s.tool, name }) catch oom();
    }
    buf.appendSlice(gpa,
        \\  }
        \\
    ) catch oom();
    // A verb is argv[1] or it is not a verb, the same rule bash spells as
    // `COMP_CWORD == 1`. PowerShell counts the word under the cursor as an
    // element once it has a character, so the tokens BEFORE it are one fewer
    // than the element count — without that adjustment `gist foo <TAB>` would
    // offer verbs in place of a path.
    if (s.verbs.len > 0) {
        buf.appendSlice(gpa,
            \\  $typed = if ($wordToComplete) { $elements.Count - 1 } else { $elements.Count }
            \\  if ($typed -eq 1) {
            \\    $verbs = @(
            \\
        ) catch oom();
        for (s.verbs) |v| {
            buf.appendSlice(gpa, "      [CompletionResult]::new('") catch oom();
            pq(buf, gpa, v.name);
            buf.appendSlice(gpa, "', '") catch oom();
            pq(buf, gpa, v.name);
            buf.appendSlice(gpa, "', [CompletionResultType]::Command, '") catch oom();
            pq(buf, gpa, v.doc);
            buf.appendSlice(gpa, "')\n") catch oom();
        }
        buf.appendSlice(gpa,
            \\    )
            \\    $hit = $verbs | Where-Object { $_.CompletionText -like "$wordToComplete*" }
            \\    if ($hit) { return $hit }
            \\  }
            \\
        ) catch oom();
    }
    buf.appendSlice(gpa,
        \\  @(
        \\
    ) catch oom();
    for (s.opts) |o| {
        var spell: std.ArrayList(u8) = .empty;
        spellings(&spell, gpa, o, "\x00");
        var it = std.mem.splitScalar(u8, spell.items, 0);
        while (it.next()) |one| {
            buf.appendSlice(gpa, "    [CompletionResult]::new('") catch oom();
            pq(buf, gpa, one);
            buf.appendSlice(gpa, "', '") catch oom();
            pq(buf, gpa, one);
            buf.appendSlice(gpa, "', [CompletionResultType]::ParameterName, '") catch oom();
            pq(buf, gpa, o.doc);
            buf.appendSlice(gpa, "')\n") catch oom();
        }
    }
    buf.appendSlice(gpa,
        \\  ) | Where-Object { $_.CompletionText -like "$wordToComplete*" }
        \\}
        \\
    ) catch oom();
}

// ── tests ────────────────────────────────────────────────────────────────

const t = std.testing;

fn render(gpa: std.mem.Allocator, comptime f: fn (*std.ArrayList(u8), std.mem.Allocator, Surface) void) []const u8 {
    var buf: std.ArrayList(u8) = .empty;
    f(&buf, gpa, primer.sample);
    return buf.items;
}

test "bash never offers a path after a switch" {
    var arena = std.heap.ArenaAllocator.init(t.allocator);
    defer arena.deinit();
    const out = render(arena.allocator(), bash);
    // ripgrep's generated bash has a `--word-regexp) compgen -f` arm. A switch
    // must not appear in the value dispatch at all.
    try t.expect(std.mem.indexOf(u8, out, "-i|--ignore-case)") == null);
    try t.expect(std.mem.indexOf(u8, out, "--heading)") == null);
    // A path-valued flag does get one, and it completes paths.
    try t.expect(std.mem.indexOf(u8, out, "-f|--file) COMPREPLY=( $(compgen -f -- \"$2\") )") != null);
}

test "bash bakes the option list at source time, not per keystroke" {
    var arena = std.heap.ArenaAllocator.init(t.allocator);
    defer arena.deinit();
    const out = render(arena.allocator(), bash);
    const assign = std.mem.indexOf(u8, out, "_demo_opts='").?;
    const func = std.mem.indexOf(u8, out, "_demo() {").?;
    try t.expect(assign < func); // top-level, outside the completion function
    try t.expect(std.mem.indexOf(u8, out, "complete -F _demo") != null);
}

test "bash splits a glued short value before it falls back to the flag list" {
    var arena = std.heap.ArenaAllocator.init(t.allocator);
    defer arena.deinit();
    const out = render(arena.allocator(), bash);
    const glued = std.mem.indexOf(u8, out, "$cur == -[!-]*").?;
    // Order is the whole trick: `-tzig` also matches the plain `-*` arm, so the
    // split has to be tried first or the value is never reached. ripgrep's
    // generated bash has no such arm and dead-ends on `-t<TAB>`.
    try t.expect(glued < std.mem.indexOf(u8, out, "$cur == -*").?);
    // The flag stays on the front of each candidate; replacing the whole word
    // with a bare value would rewrite `-tzig` to `zig`.
    try t.expect(std.mem.indexOf(u8, out, "COMPREPLY[i]=$glued${COMPREPLY[i]}") != null);
}

test "bash holds the undo spellings back until --no is typed" {
    var arena = std.heap.ArenaAllocator.init(t.allocator);
    defer arena.deinit();
    const out = render(arena.allocator(), bash);
    try t.expect(std.mem.indexOf(u8, out, "$cur == --no*") != null);
    try t.expect(std.mem.indexOf(u8, out, "_demo_undo=") != null);
}

test "a verb is offered at argv[1] and nowhere else, in all three shells" {
    var arena = std.heap.ArenaAllocator.init(t.allocator);
    defer arena.deinit();
    const gpa = arena.allocator();
    // `gist -w index` searches for "index"; it does not run the index verb. A
    // completion that offers the verb after a flag advertises a behavior the
    // parser will not perform, which is worse than offering nothing.
    //
    // fish's own `__fish_use_subcommand` is the git rule (`git -C dir status`
    // runs the verb) and skips leading flags, so naming it here would be the
    // bug. Each shell states the same rule in its own dialect.
    const fish_out = render(gpa, fish);
    try t.expect(std.mem.indexOf(u8, fish_out, "-n __fish_is_first_arg -a 'index'") != null);
    try t.expect(std.mem.indexOf(u8, fish_out, "__fish_use_subcommand") == null);

    try t.expect(std.mem.indexOf(u8, render(gpa, bash), "(( COMP_CWORD == 1 ))") != null);
    try t.expect(std.mem.indexOf(u8, render(gpa, powershell), "if ($typed -eq 1) {") != null);
}

test "powershell counts the word under the cursor before deciding it is argv[1]" {
    var arena = std.heap.ArenaAllocator.init(t.allocator);
    defer arena.deinit();
    const out = render(arena.allocator(), powershell);
    // Without the adjustment, `gist foo <TAB>` (two elements, empty word) and
    // `gist in<TAB>` (two elements, one being typed) are indistinguishable, and
    // the first would offer verbs where a path belongs.
    try t.expect(std.mem.indexOf(u8, out, "if ($wordToComplete) { $elements.Count - 1 } else { $elements.Count }") != null);
    // The verb list is filtered and returned only on a hit, so a non-verb first
    // word still falls through to the flag list rather than dead-ending.
    try t.expect(std.mem.indexOf(u8, out, "if ($hit) { return $hit }") != null);
}

test "fish ships a gloss beside every baked candidate" {
    var arena = std.heap.ArenaAllocator.init(t.allocator);
    defer arena.deinit();
    const out = render(arena.allocator(), fish);
    try t.expect(std.mem.indexOf(u8, out, "'auto\twhen stdout is a terminal'") != null);
    try t.expect(std.mem.indexOf(u8, out, "-s i -l ignore-case") != null);
    // A file-valued flag delegates to fish's own path completion.
    try t.expect(std.mem.indexOf(u8, out, "-s f -l file -r -F") != null);
}

test "powershell carries the doc as a tooltip on every spelling" {
    var arena = std.heap.ArenaAllocator.init(t.allocator);
    defer arena.deinit();
    const out = render(arena.allocator(), powershell);
    try t.expect(std.mem.indexOf(u8, out, "Register-ArgumentCompleter -Native -CommandName 'demo'") != null);
    try t.expect(std.mem.indexOf(u8, out, "'match case-insensitively'") != null);
    try t.expect(std.mem.indexOf(u8, out, "ParameterValue") != null);
}

test "quoting survives an apostrophe in every shell's own grammar" {
    var arena = std.heap.ArenaAllocator.init(t.allocator);
    defer arena.deinit();
    const gpa = arena.allocator();
    inline for (.{ .{ sq, "it'\\''s" }, .{ fq, "it\\'s" }, .{ pq, "it''s" } }) |c| {
        var buf: std.ArrayList(u8) = .empty;
        c[0](&buf, gpa, "it's");
        try t.expectEqualStrings(c[1], buf.items);
    }
}
